name: dotnet package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: xt0rted/setup-dotnet@v1.0.0
        with:
          dotnet-version: "8.0.101"
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build
